### ISSUE TITLE
[Bug] Clusters from 0.7 may crash in 0.9

### ISSUE THREAD

**Issue by JGSweets** [skypilot-org/skypilot#5439]
When launching with Skypilot 0.9.1, I received this error:
> `AttributeError: 'Kubernetes' object has no attribute 'LEGACY_SINGLETON_REGION'`

This resulted in a zombie instance that was not connected to any live service as well. Likely because the service never completed the `up` command. This zombie situation may be specific to us.

Notes:
This was connected to a directory that had previously launched with skypilot < 0.7.0.

TB line: `".../sky/backends/backend_utils.py", line 2922, in get_endpoints`

**Comment by SeungjinYang** [comment]
Created a cluster on 0.6.0 - works on 0.7.0, 0.8.0 - failed on 0.9.0/0.9.1 due to `LEGACY_SINGLETON_REGION`
Creared a cluster on 0.8.0 - works on 0.8.0, failed on 0.9.0/0.9.1 due to `LEGACY_SINGLETON_REGION`

**Comment by cg505** [comment]
Released [v0.9.2](https://github.com/skypilot-org/skypilot/releases/tag/v0.9.2) to address this! If you hit it, please upgrade.
