### ISSUE TITLE
Shell complete error after upgrading to v0.2

### ISSUE THREAD

**Issue by pounde** [skypilot-org/skypilot#1252]
Receive the following error after upgrading to v0.2:
`(xv2_api) lb@LBsMBP ~ % sky status
Traceback (most recent call last):
  File "/Users/lb/miniconda3/envs/xv2_api/bin/sky", line 5, in <module>
    from sky.cli import cli
  File "/Users/lb/miniconda3/envs/xv2_api/lib/python3.8/site-packages/sky/cli.py", line 1017, in <module>
    def launch(
  File "/Users/lb/miniconda3/envs/xv2_api/lib/python3.8/site-packages/click/decorators.py", line 192, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/Users/lb/miniconda3/envs/xv2_api/lib/python3.8/site-packages/click/core.py", line 1714, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'shell_complete'`

Attempted to install shell-complete and received the same error:
`(xv2_api) lb@LBsMBP ~ % sky --install-shell-completion auto
Traceback (most recent call last):
  File "/Users/lb/miniconda3/envs/xv2_api/bin/sky", line 5, in <module>
    from sky.cli import cli
  File "/Users/lb/miniconda3/envs/xv2_api/lib/python3.8/site-packages/sky/cli.py", line 1017, in <module>
    def launch(
  File "/Users/lb/miniconda3/envs/xv2_api/lib/python3.8/site-packages/click/decorators.py", line 192, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/Users/lb/miniconda3/envs/xv2_api/lib/python3.8/site-packages/click/core.py", line 1714, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'shell_complete'`

Running on Mac OS 12.5.1, Python 3.8.13, installed via pip. Attempted a local install with the same results.

**Comment by concretevitamin** [comment]
Thanks @pounde. What does this show?
```
python -c 'import click; print(click.__version__)'   
```

I'm guessing it's below version 8.  I'll send a PR shortly to pin the click version so `shell_complete` is available.

In the meantime, could you try:
```
pip install --upgrade click==8.0.4     
```

**Comment by pounde** [comment]
@concretevitamin - sure enough. I'm running 7.1.2. Upgrading is causing some incompatabilites with a different package. I'll work that out and report back. Thanks!

**Comment by Michaelvll** [comment]
Hey @pounde, the problem should be fixed in #1261. Please feel free to have a try for it, when you get time by
```
git clone https://github.com/skypilot-org/skypilot
cd skypilot
pip install -e .
```

**Comment by pounde** [comment]
I'm working in a new env now but it seems to be working fine. Thank you.
