### PR TITLE
Specify 'click' version in setup.py.

### LINKED ISSUE #1252: Shell complete error after upgrading to v0.2
Receive the following error after upgrading to v0.2:
`(xv2_api) lb@LBsMBP ~ % sky status
Traceback (most recent call last):
  File "/Users/lb/miniconda3/envs/xv2_api/bin/sky", line 5, in <module>
    from sky.cli import cli
  File "/Users/lb/miniconda3/envs/xv2_api/lib/python3.8/site-packages/sky/cli.py", line 1017, in <module>
    def launch(
  File "/Users/lb/miniconda3/envs/xv2_api/lib/python3.8/site-packages/click/decorators.py", line 192, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/Users/lb/miniconda3/envs/xv2_api/lib/python3.8/site-packages/click/core.py", line 1714, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'shell_complete'`

Attempted to install shell-complete and received the same error:
`(xv2_api) lb@LBsMBP ~ % sky --install-shell-completion auto
Traceback (most recent call last):
  File "/Users/lb/miniconda3/envs/xv2_api/bin/sky", line 5, in <module>
    from sky.cli import cli
  File "/Users/lb/miniconda3/envs/xv2_api/lib/python3.8/site-packages/sky/cli.py", line 1017, in <module>
    def launch(
  File "/Users/lb/miniconda3/envs/xv2_api/lib/python3.8/site-packages/click/decorators.py", line 192, in decorator
    _param_memo(f, OptionClass(param_decls, **option_attrs))
  File "/Users/lb/miniconda3/envs/xv2_api/lib/python3.8/site-packages/click/core.py", line 1714, in __init__
    Parameter.__init__(self, param_decls, type=type, **attrs)
TypeError: __init__() got an unexpected keyword argument 'shell_complete'`

Running on Mac OS 12.5.1, Python 3.8.13, installed via pip. Attempted a local install with the same results.

### PR DESCRIPTION
**Pull request by concretevitamin**
Fixes #1252 (thanks @pounde for reporting!).  

cc @iojw 

Tested:
- uninstalled click, then re-ran `pip install -e .` and ran `sky`

### CODE REVIEW

**Review by iojw — APPROVED** [review]
Looks good to me, thank you for fixing this!

**Comment by Michaelvll** [comment]
Just wondering if we can change the argument name we used for the shell completion. It seems like the only difference for the `7.x` and `8.x` for shell completion is that `autocompletion=xx` ([Click 7.x](https://click.palletsprojects.com/en/7.x/bashcomplete/)) vs `shell_completion=xx`([Click 8.x](https://click.palletsprojects.com/en/8.1.x/shell-completion/)). From my gut, it would be better to avoid strict version constraints if it is not hard to support the older version.

**Comment by iojw** [comment]
@Michaelvll There are pretty fundamental changes to shell completion in click 8.0 beyond just the argument name - the shell completion was redesigned, changing the completion interface and installation method too (https://click.palletsprojects.com/en/8.1.x/changes/) so I think it will be difficult to support both versions.

Potentially, we could use some sort of dictionary to only pass in the `shell_complete` argument when click is >=8.0 ?

**Comment by concretevitamin** [comment]
> I think it is also fine to go without the shell completion when we detect the user using older click, to unblock the usage of core sky functionalities.

> Potentially, we could use some sort of dictionary to only pass in the shell_complete argument when click is >=8.0 ?

I'll hold off merging this. @iojw: is the second proposal the same as the first? If you have time, can you take a stab at that?

**Comment by Michaelvll** [comment]
> Potentially, we could use some sort of dictionary to only pass in the `shell_complete` argument when click is >=8.0 ?

If the first option does not work, I think this one should be good enough. Please go ahead and have a try on that @iojw. ;)

**Comment by iojw** [comment]
Fixed by #1261.
