### PR TITLE
Awscliv2 dependency install from source

### PR DESCRIPTION
**Pull request by zpoint**
bug reproduce:

```
# activate conda
cd docs
pip install -r requirements-docs.txt
cd ..
pip install -e .[all]
cd docs
./build.sh
```

output:

```
    'meta': (nodes.meta, 'docutils.nodes.meta'),  # type: ignore[attr-defined]
AttributeError: module 'docutils.nodes' has no attribute 'meta'
make: *** [html] Error 1
```

Its because `awscli>=1.27.10`  requires `docutils<0.17,>=0.10`, while our doc build use `sphinx==7.1.2`  which requires `docutils<0.21,>=0.18.1`
`pip install -e .[all]`  gets `docutils==0.16` from `awscli>=1.27.10`
`pip install -r requirements-docs.txt` gets `docutils==0.19` from `sphinx==7.1.2`
The doc build only works with `docutils==0.19`

Profile:

```bash
pip install git+https://github.com/aws/aws-cli.git@v2  18.50s user 10.30s system 57% cpu 49.714 total
pip install 'awscli>=1.27.10'  1.36s user 0.56s system 77% cpu 2.468 total
```

30 seconds slower install from source

[They are not publishing this to pypi](https://github.com/aws/aws-cli/issues/4947), if we want to install it we should install from source

Tested (run the relevant ones):

- [ ] Code formatting: `bash format.sh`
- [ ] Any manual or new tests for this PR (please specify below)
- [ ] All smoke tests: `pytest tests/test_smoke.py` 
- [ ] Relevant individual smoke tests: `pytest tests/test_smoke.py::test_fill_in_the_name` 
- [ ] Backward compatibility tests: `conda deactivate; bash -i tests/backward_compatibility_tests.sh`

### CODE REVIEW

**Comment by zpoint** [comment]
Dependency upgrades should be approached with more caution, especially when installing from source, as the gain might not be worth it. It might be better to keep the existing build inconvenience as it is.
