### PR TITLE
Fix worker exits on duplicate scheduling

### LINKED ISSUE #5609: API server does not start enough handler workers
When launching an API server with multiple workers, the following error will be raised and only one uvicorn worker will successfully started:

```
I 05-17 08:28:20 on.py:48] Waiting for application startup.
E 05-17 08:28:20 on.py:121] Traceback (most recent call last):
E 05-17 08:28:20 on.py:121]   File "/Users/aylei/repo/skypilot-org/skypilot/sky/server/server.py", line 146, in lifespan
E 05-17 08:28:20 on.py:121]     executor.schedule_request(
E 05-17 08:28:20 on.py:121]   File "/Users/aylei/repo/skypilot-org/skypilot/sky/server/requests/executor.py", line 488, in schedule_request
E 05-17 08:28:20 on.py:121]     prepare_request(request_id, request_name, request_body, func,
E 05-17 08:28:20 on.py:121]   File "/Users/aylei/repo/skypilot-org/skypilot/sky/server/requests/executor.py", line 450, in prepare_request
E 05-17 08:28:20 on.py:121]     raise exceptions.RequestAlreadyExistsError(
E 05-17 08:28:20 on.py:121] AttributeError: module 'sky.exceptions' has no attribute 'RequestAlreadyExistsError'
E 05-17 08:28:20 on.py:121]
E 05-17 08:28:20 on.py:121] During handling of the above exception, another exception occurred:
E 05-17 08:28:20 on.py:121]
E 05-17 08:28:20 on.py:121] Traceback (most recent call last):
E 05-17 08:28:20 on.py:121]   File "/opt/homebrew/anaconda3/envs/sky/lib/python3.10/site-packages/starlette/routing.py", line 693, in lifespan
E 05-17 08:28:20 on.py:121]     async with self.lifespan_context(app) as maybe_state:
E 05-17 08:28:20 on.py:121]   File "/opt/homebrew/anaconda3/envs/sky/lib/python3.10/contextlib.py", line 199, in __aenter__
E 05-17 08:28:20 on.py:121]     return await anext(self.gen)
E 05-17 08:28:20 on.py:121]   File "/opt/homebrew/anaconda3/envs/sky/lib/python3.10/site-packages/fastapi/routing.py", line 133, in merged_lifespan
E 05-17 08:28:20 on.py:121]     async with original_context(app) as maybe_original_state:
E 05-17 08:28:20 on.py:121]   File "/opt/homebrew/anaconda3/envs/sky/lib/python3.10/contextlib.py", line 199, in __aenter__
E 05-17 08:28:20 on.py:121]     return await anext(self.gen)
E 05-17 08:28:20 on.py:121]   File "/opt/homebrew/anaconda3/envs/sky/lib/python3.10/site-packages/fastapi/routing.py", line 133, in merged_lifespan
E 05-17 08:28:20 on.py:121]     async with original_context(app) as maybe_original_state:
E 05-17 08:28:20 on.py:121]   File "/opt/homebrew/anaconda3/envs/sky/lib/python3.10/contextlib.py", line 199, in __aenter__
E 05-17 08:28:20 on.py:121]     return await anext(self.gen)
E 05-17 08:28:20 on.py:121]   File "/Users/aylei/repo/skypilot-org/skypilot/sky/server/server.py", line 154, in lifespan
E 05-17 08:28:20 on.py:121]     except exceptions.RequestAlreadyExistsError:
E 05-17 08:28:20 on.py:121] AttributeError: module 'sky.exceptions' has no attribute 'RequestAlreadyExistsError'
E 05-17 08:28:20 on.py:121]
E 05-17 08:28:20 on.py:59] Application startup failed. Exiting.
```

This is a regression introduced by https://github.com/skypilot-org/skypilot/pull/5582

### PR DESCRIPTION
**Pull request by aylei**
close #5609 

follow up: https://github.com/skypilot-org/skypilot/issues/5610

Tested (run the relevant ones):

- [x] Code formatting: install pre-commit (auto-check on commit) or `bash format.sh`
- [x] Manually tested locally, no error is raised
```
(sky) ➜  skypilot git:(fix-duplicate-scheduling) sky api start --deploy
Failed to connect to SkyPilot API server at http://0.0.0.0:46580. Starting a local server.
✓ SkyPilot API server started.
├── SkyPilot API server: http://0.0.0.0:46580 Dashboard: http://0.0.0.0:46580/dashboard
└── View API server logs at: ~/.sky/api_server/server.log
(sky) ➜  skypilot git:(fix-duplicate-scheduling) cat ~/.sky/api_server/server.log
I 05-17 08:34:23 config.py:143] SkyPilot API server will start 12 server processes with 21 background workers for long requests and will allow at max 22 short requests in parallel.
I 05-17 08:34:23 executor.py:514] Creating shared request queues
I 05-17 08:34:23 mp_queue.py:74] Waiting for request queue, named 'long', to be ready...
I 05-17 08:34:23 mp_queue.py:74] Waiting for request queue, named 'long', to be ready...
I 05-17 08:34:23 mp_queue.py:74] Waiting for request queue, named 'long', to be ready...
I 05-17 08:34:23 mp_queue.py:74] Waiting for request queue, named 'long', to be ready...
I 05-17 08:34:23 executor.py:539] Request queues created
INFO:__main__:Starting SkyPilot API server, workers=12
INFO:     Uvicorn running on http://0.0.0.0:46580 (Press CTRL+C to quit)
INFO:     Started parent process [94605]
I 05-17 08:34:24 server.py:83] Started server process [94633]
I 05-17 08:34:24 on.py:48] Waiting for application startup.
I 05-17 08:34:24 executor.py:493] Queuing request: skypilot-status-refresh-daemon
I 05-17 08:34:24 on.py:62] Application startup complete.
I 05-17 08:34:24 httptools_impl.py:476] 127.0.0.1:55919 - "GET /api/health HTTP/1.1" 200
I 05-17 08:34:24 executor.py:167] [Worker(schedule_type=short)] Submitting request: skypilot-status-refresh-daemon
I 05-17 08:34:24 executor.py:177] [Worker(schedule_type=short)] Submitted request: skypilot-status-refresh-daemon
I 05-17 08:34:25 executor.py:299] Running request skypilot-status-refresh-daemon with pid 9463
```
- [ ] All smoke tests: `/smoke-test` (CI) or `pytest tests/test_smoke.py` (local)
- [ ] Relevant individual tests: `/smoke-test -k test_name` (CI) or `pytest tests/test_smoke.py::test_name` (local)
- [ ] Backward compatibility: `/quicktest-core` (CI) or `pytest tests/smoke_tests/test_backward_compat.py` (local)

### CODE REVIEW

**Review by cg505 — APPROVED** [review]
Can we follow up and avoid the path that causes this duplicate submission?

**Comment by aylei** [comment]
> Can we follow up and avoid the path that causes this duplicate submission?

Created a ticket for this https://github.com/skypilot-org/skypilot/issues/5612, currently we require the code in `lifespan` to be idempotent
