### ISSUE TITLE
API server does not start enough handler workers

### ISSUE THREAD

**Issue by aylei** [skypilot-org/skypilot#5609]
When launching an API server with multiple workers, the following error will be raised and only one uvicorn worker will successfully started:

```
I 05-17 08:28:20 on.py:48] Waiting for application startup.
E 05-17 08:28:20 on.py:121] Traceback (most recent call last):
E 05-17 08:28:20 on.py:121]   File "/Users/aylei/repo/skypilot-org/skypilot/sky/server/server.py", line 146, in lifespan
E 05-17 08:28:20 on.py:121]     executor.schedule_request(
E 05-17 08:28:20 on.py:121]   File "/Users/aylei/repo/skypilot-org/skypilot/sky/server/requests/executor.py", line 488, in schedule_request
E 05-17 08:28:20 on.py:121]     prepare_request(request_id, request_name, request_body, func,
E 05-17 08:28:20 on.py:121]   File "/Users/aylei/repo/skypilot-org/skypilot/sky/server/requests/executor.py", line 450, in prepare_request
E 05-17 08:28:20 on.py:121]     raise exceptions.RequestAlreadyExistsError(
E 05-17 08:28:20 on.py:121] AttributeError: module 'sky.exceptions' has no attribute 'RequestAlreadyExistsError'
E 05-17 08:28:20 on.py:121]
E 05-17 08:28:20 on.py:121] During handling of the above exception, another exception occurred:
E 05-17 08:28:20 on.py:121]
E 05-17 08:28:20 on.py:121] Traceback (most recent call last):
E 05-17 08:28:20 on.py:121]   File "/opt/homebrew/anaconda3/envs/sky/lib/python3.10/site-packages/starlette/routing.py", line 693, in lifespan
E 05-17 08:28:20 on.py:121]     async with self.lifespan_context(app) as maybe_state:
E 05-17 08:28:20 on.py:121]   File "/opt/homebrew/anaconda3/envs/sky/lib/python3.10/contextlib.py", line 199, in __aenter__
E 05-17 08:28:20 on.py:121]     return await anext(self.gen)
E 05-17 08:28:20 on.py:121]   File "/opt/homebrew/anaconda3/envs/sky/lib/python3.10/site-packages/fastapi/routing.py", line 133, in merged_lifespan
E 05-17 08:28:20 on.py:121]     async with original_context(app) as maybe_original_state:
E 05-17 08:28:20 on.py:121]   File "/opt/homebrew/anaconda3/envs/sky/lib/python3.10/contextlib.py", line 199, in __aenter__
E 05-17 08:28:20 on.py:121]     return await anext(self.gen)
E 05-17 08:28:20 on.py:121]   File "/opt/homebrew/anaconda3/envs/sky/lib/python3.10/site-packages/fastapi/routing.py", line 133, in merged_lifespan
E 05-17 08:28:20 on.py:121]     async with original_context(app) as maybe_original_state:
E 05-17 08:28:20 on.py:121]   File "/opt/homebrew/anaconda3/envs/sky/lib/python3.10/contextlib.py", line 199, in __aenter__
E 05-17 08:28:20 on.py:121]     return await anext(self.gen)
E 05-17 08:28:20 on.py:121]   File "/Users/aylei/repo/skypilot-org/skypilot/sky/server/server.py", line 154, in lifespan
E 05-17 08:28:20 on.py:121]     except exceptions.RequestAlreadyExistsError:
E 05-17 08:28:20 on.py:121] AttributeError: module 'sky.exceptions' has no attribute 'RequestAlreadyExistsError'
E 05-17 08:28:20 on.py:121]
E 05-17 08:28:20 on.py:59] Application startup failed. Exiting.
```

This is a regression introduced by https://github.com/skypilot-org/skypilot/pull/5582
